apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: MyAutomation

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    steps:
      - name: Checkout Repository
        uses: cloudbees-io/checkout@v1
      - name: Build and Test
        run: |
          echo "Building and testing your code..."
      - name: Deploy
        run: |
          echo "Deploying your application..."
